### PR TITLE
check if path is null

### LINKED ISSUE #77: Null exceptions when the player tries again after dying
The NPCs have a lot of null exceptions after i press try again if i die

### PR DESCRIPTION
**Pull request by EvanDime**
when returning to the scene there are times when the path is null on load
closes #77

### CODE REVIEW

File: Assets/Scripts/NPCs/StateMachine/States/Wander.cs [hunk 1]
```diff
@@ -113,6 +113,11 @@ private void MoveTowardsTarget()
 
         private bool TargetReached()
         {
+            if (_pathToTarget == null)
```
Comment (ClaudiaLapalme) [inline Assets/Scripts/NPCs/StateMachine/States/Wander.cs]: I think that this is just putting a band aid on the problem (which doesn't reaallyyy help because the list is initialized so you should also check Count < 1). The problem is that the NPCs are not being removed and reinitialized once the player decides to play again.

Comment (EvanDime) [reply Assets/Scripts/NPCs/StateMachine/States/Wander.cs]: Changing the script order in the meta files seems to resolve this issue entirely.

**Review by f-michaut — APPROVED** [review]

**Review by ClaudiaLapalme — DISMISSED** [review]
After discussion, the band aid seems to make the most sense atm

**Comment by ClaudiaLapalme** [comment]
I'll approve once the mother PR is merged because i don't want to deal with merge conflicts in it

**Review by tedgag — APPROVED** [review]
No errors here
